name: Tests

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { name: '3.10', python: '3.10', os: ubuntu-latest, tox: 'python3.10' }
          - { name: '3.9', python: '3.9', os: ubuntu-latest, tox: 'python3.9' }
          - { name: '3.8', python: '3.8', os: ubuntu-latest, tox: 'python3.8' }
          - { name: '3.7', python: '3.7', os: ubuntu-latest, tox: 'python3.7' }
          - { name: 'typing', python: '3.10', os: ubuntu-latest, tox: 'typing' }
          - { name: 'style', python: '3.10', os: ubuntu-latest, tox: 'style' }

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install -U wheel setuptools pip tox
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: tox -e ${{ matrix.tox }}
